[package]
name = "tinyvm"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.release-debuginfo]
inherits = "release"
strip = "none"
debug = 1

[profile.dev-fast]
inherits = "dev"
strip = "debuginfo"
debug = 0

[lib]
name = "tinyvm"
path = "src/lib.rs"

[[bin]]
name = "tinyvm"
path = "src/main.rs"
